insert into type(name) values('молочный продукт');
insert into type(name) values('мясо');
insert into type(name) values('овощи');
insert into type(name) values('хлебобулочные изделия');
insert into type(name) values('сыр');

insert into product(name, type_id, expired_date, price) values('Мороженное сливочное', 1, make_date(2021, 4, 25), 50);
insert into product(name, type_id, expired_date, price) values('Мороженное сливочное', 1, make_date(2021, 4, 25), 50);
insert into product(name, type_id, expired_date, price) values('Мороженное сливочное', 1, make_date(2021, 4, 25), 50);
insert into product(name, type_id, expired_date, price) values('Мороженное сливочное', 1, make_date(2021, 4, 25), 50);
insert into product(name, type_id, expired_date, price) values('Мороженное сливочное', 1, make_date(2021, 4, 25), 50);
insert into product(name, type_id, expired_date, price) values('Мороженное сливочное', 1, make_date(2021, 4, 25), 50);
insert into product(name, type_id, expired_date, price) values('Молоко', 1, make_date(2021, 3, 25), 45);
insert into product(name, type_id, expired_date, price) values('Молоко', 1, make_date(2021, 3, 25), 45);
insert into product(name, type_id, expired_date, price) values('Молоко', 1, make_date(2021, 3, 25), 45);
insert into product(name, type_id, expired_date, price) values('Молоко', 1, make_date(2021, 3, 25), 45);
insert into product(name, type_id, expired_date, price) values('Молоко', 1, make_date(2021, 3, 25), 45);
insert into product(name, type_id, expired_date, price) values('Молоко', 1, make_date(2021, 3, 25), 45);
insert into product(name, type_id, expired_date, price) values('Сыр российский', 5, make_date(2021, 4, 15), 250);
insert into product(name, type_id, expired_date, price) values('Сыр российский', 5, make_date(2021, 4, 15), 250);
insert into product(name, type_id, expired_date, price) values('Сыр российский', 5, make_date(2021, 4, 15), 250);
insert into product(name, type_id, expired_date, price) values('Сыр российский', 5, make_date(2021, 4, 15), 250);
insert into product(name, type_id, expired_date, price) values('Сыр российский', 5, make_date(2021, 4, 15), 250);
insert into product(name, type_id, expired_date, price) values('Сыр российский', 5, make_date(2021, 4, 15), 250);
insert into product(name, type_id, expired_date, price) values('Сыр российский', 5, make_date(2021, 4, 15), 250);
insert into product(name, type_id, expired_date, price) values('Сыр российский', 5, make_date(2021, 4, 15), 250);
insert into product(name, type_id, expired_date, price) values('Сыр российский', 5, make_date(2021, 4, 15), 250);
insert into product(name, type_id, expired_date, price) values('Сыр российский', 5, make_date(2021, 4, 15), 250);
insert into product(name, type_id, expired_date, price) values('Мясо мороженное', 2, make_date(2021, 4, 22), 200);
insert into product(name, type_id, expired_date, price) values('Мясо свежее', 2, make_date(2021, 3, 22), 300);
insert into product(name, type_id, expired_date, price) values('Мясо мороженное', 2, make_date(2021, 4, 22), 200);
insert into product(name, type_id, expired_date, price) values('Мясо свежее', 2, make_date(2021, 3, 22), 300);
insert into product(name, type_id, expired_date, price) values('Мясо мороженное', 2, make_date(2021, 4, 22), 200);
insert into product(name, type_id, expired_date, price) values('Мясо свежее', 2, make_date(2021, 3, 22), 300);
insert into product(name, type_id, expired_date, price) values('Мясо мороженное', 2, make_date(2021, 4, 22), 200);
insert into product(name, type_id, expired_date, price) values('Мясо свежее', 2, make_date(2021, 3, 22), 300);
insert into product(name, type_id, expired_date, price) values('Мясо мороженное', 2, make_date(2021, 4, 22), 200);
insert into product(name, type_id, expired_date, price) values('Мясо свежее', 2, make_date(2021, 3, 22), 300);
insert into product(name, type_id, expired_date, price) values('Мясо мороженное', 2, make_date(2021, 4, 22), 200);
insert into product(name, type_id, expired_date, price) values('Мясо свежее', 2, make_date(2021, 3, 22), 300);
insert into product(name, type_id, expired_date, price) values('Мясо мороженное', 2, make_date(2021, 4, 22), 200);
insert into product(name, type_id, expired_date, price) values('Мясо свежее', 2, make_date(2021, 3, 22), 300);
insert into product(name, type_id, expired_date, price) values('Мясо мороженное', 2, make_date(2021, 4, 22), 200);
insert into product(name, type_id, expired_date, price) values('Мясо свежее', 2, make_date(2021, 3, 22), 300);
insert into product(name, type_id, expired_date, price) values('Мясо мороженное', 2, make_date(2021, 4, 22), 200);
insert into product(name, type_id, expired_date, price) values('Мясо свежее', 2, make_date(2021, 3, 22), 300);
insert into product(name, type_id, expired_date, price) values('Мясо мороженное', 2, make_date(2021, 4, 22), 200);
insert into product(name, type_id, expired_date, price) values('Мясо свежее', 2, make_date(2021, 3, 22), 300);
insert into product(name, type_id, expired_date, price) values('Помидоры', 3, make_date(2021, 3, 28), 20);
insert into product(name, type_id, expired_date, price) values('Лук', 3, make_date(2021, 4, 5), 10);
insert into product(name, type_id, expired_date, price) values('Лук', 3, make_date(2021, 4, 5), 10);
insert into product(name, type_id, expired_date, price) values('Лук', 3, make_date(2021, 4, 5), 10);
insert into product(name, type_id, expired_date, price) values('Лук', 3, make_date(2021, 4, 5), 10);
insert into product(name, type_id, expired_date, price) values('Лук', 3, make_date(2021, 4, 5), 10);
insert into product(name, type_id, expired_date, price) values('Лук', 3, make_date(2021, 4, 5), 10);
insert into product(name, type_id, expired_date, price) values('Лук', 3, make_date(2021, 4, 5), 10);
insert into product(name, type_id, expired_date, price) values('Лук', 3, make_date(2021, 4, 5), 10);
insert into product(name, type_id, expired_date, price) values('Лук', 3, make_date(2021, 4, 5), 10);
insert into product(name, type_id, expired_date, price) values('Лук', 3, make_date(2021, 4, 5), 10);
insert into product(name, type_id, expired_date, price) values('Хлеб белый', 4, make_date(2021, 3, 23), 25.2);
insert into product(name, type_id, expired_date, price) values('Хлеб серый', 4, make_date(2021, 3, 24), 20);